development:
  adapter: postgresql
  database: demo_development
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: demo_test
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
  encoding: unicode
  host: localhost
  pool: 5